language: python
python: "3.6"

sudo: required

services:
  - docker
  - postgresql

before_script:
  - psql -c 'create database cuve;'  -U postgres

install:
  - pip install -r requirements.txt -r requirements.dev.txt
  - pip install -e .

jobs:
  include:
    - stage: lint and test
    - script: flake8
    - script: pytest -vs --config=./etc/config/travis.yml --createdb

    - stage: build
    - script: docker build -t cuve/order-service .
