language: python
python: "3.6"

sudo: required

services:
  - docker

install: pip install --user -r requirements.txt -r requirements.dev.txt
script:
  - flake8
  - pytest -vs

after_success:
  - docker build -t cuve/order-service .
