version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=cuve
      - POSTGRES_PASSWORD=cuve
      - POSTGRES_DB=cuve

  api:
    build: .
    image: cuve/order
    command: cuve.order --config /app/etc/config/development.yml server --host 0.0.0.0 --port 8080

    ports:
      - 8080:8080
    links:
      - postgres
    volumes:
      - ./cuve:/app/cuve
      - ./etc:/app/etc
      - ./tests:/app/tests

      # FIXME: Creates directory on mount
      # - ./setup.py:/app/setup.py
      # - ./requierments.txt:/app/requierments.txt
      # - ./requierments.dev.txt:/app/requierments.dev.txt

    stdin_open: true
    tty: true
